#line 2 "test.c"

#line 4 "test.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 51
#define YY_END_OF_BUFFER 52
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[267] =
    {   0,
       44,   44,   52,   50,    1,    2,   31,   49,   25,   29,
       46,   32,   33,   24,   38,   24,   50,   25,    5,   39,
       26,   30,   26,   40,   40,   36,   37,   29,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   34,   29,
       35,    1,   26,   49,   41,   49,   28,   46,   45,    0,
       27,    6,    0,    4,   43,    5,   44,   43,   29,   40,
       40,    0,    0,   40,   40,   40,   40,   40,   40,   13,
       40,   40,   40,   18,   40,   40,   40,   40,   40,    0,
        0,   46,    7,    0,    0,   47,    0,   46,   46,   46,
        0,    6,   43,   48,    0,    0,    4,    3,    4,    6,

       43,   43,    0,    6,   43,   43,    0,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   17,   19,   40,   40,
       40,   40,   46,   46,    0,    0,    0,   42,    0,   43,
        0,    6,    4,    3,    6,   43,   43,   43,   43,   43,
        0,   43,   43,    0,   43,   43,   43,   43,   40,   40,
        9,   10,   40,   40,   40,   15,   40,   40,   40,   23,
       40,   42,   43,   42,   43,    0,   43,    4,    4,   43,
        0,    6,   43,    0,   43,   43,   43,   43,   43,   43,
       43,    0,   43,   43,   43,   43,   40,    8,   40,   40,
       40,   16,   40,   40,   22,   43,   42,    0,   43,   43,

       43,   43,   43,    4,   43,    0,   43,   43,    0,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   40,   40,
       14,   20,   21,   43,    0,   43,   43,   43,   43,   43,
        0,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   40,   12,   43,   43,   43,   43,   43,   43,
        0,   43,   43,   43,   43,   43,   43,   11,   43,   43,
       43,   43,   43,   43,   43,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,    7,   21,   22,
       23,   24,    7,    7,   25,   25,   25,   25,   26,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       27,   28,   29,   30,   25,    7,   31,   32,   33,   34,

       35,   36,   25,   37,   38,   25,   39,   40,   25,   41,
       42,   25,   25,   43,   44,   45,   46,   47,   48,   25,
       25,   25,   49,   50,   51,    7,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[52] =
    {   0,
        1,    1,    2,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    4,    3,    5,    5,
        3,    3,    3,    3,    5,    5,    3,    3,    3,    3,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    3,    3,
        3
    } ;

static const flex_int16_t yy_base[280] =
    {   0,
        0,    0,  319,  955,   50,  955,  289,   47,  955,  293,
       45,  955,  955,  272,  955,  266,   37,   45,   42,  955,
       42,  247,   43,   50,   62,  955,  955,  955,   52,   65,
       68,  176,   71,   73,   80,   78,   85,   97,  955,  154,
      955,  104,  955,   95,  112,  116,  955,   84,  110,  139,
      955,  111,  123,  122,  113,  134,  142,  171,  955,    0,
      123,  146,  136,  157,  159,  153,  176,  179,  181,  183,
      186,  189,  191,  193,  195,  199,  203,  205,  207,  129,
      229,  211,  218,  252,  223,  226,  294,  227,  228,  336,
      228,  233,  247,  259,  263,  163,  161,  955,  165,  270,

      259,  284,  259,  289,  297,  301,  272,  324,  314,  328,
      309,  330,  334,  337,  339,  342,  291,  351,  365,  367,
      369,  373,  232,  142,  350,    0,    0,  379,  371,  387,
      375,  398,  955,  119,  402,  415,   48,   54,  422,  423,
      381,  425,  436,  389,  434,  445,  451,  406,  447,  455,
      427,  443,  459,  461,  464,  468,  470,  473,  476,  479,
      482,  486,  366,  494,  505,  499,  514,   96,  246,  518,
      507,  522,  272,  524,  530,  539,  543,  526,  547,  551,
      555,  532,  560,  565,  575,  583,  494,  568,  585,  587,
      589,  592,  594,  596,  598,  955,  602,  610,  619,  627,

      631,  612,  633,   93,  641,  636,  655,  653,  643,  645,
      658,  663,  671,  582,  675,  680,  683,  685,  688,  693,
      697,  699,  702,  706,  708,  710,  716,  720,  729,  609,
      733,  737,  745,  749,  751,  754,  759,  771,  762,  767,
      955,  779,  781,  784,  791,  801,  793,  803,  955,  811,
      805,  813,  815,  823,  837,  626,  828,  840,  845,  849,
      853,  857,  863,  955,  873,  955,  908,  911,  913,   81,
      918,  921,  924,  929,  934,   55,  939,  944,  949
    } ;

static const flex_int16_t yy_def[280] =
    {   0,
      266,    1,  266,  266,  266,  266,  266,  267,  266,  266,
      268,  266,  266,  266,  266,  266,  266,  266,  269,  266,
      266,  266,  266,  270,  270,  266,  266,  266,  270,  270,
      270,   25,  270,  270,  270,  270,  270,  270,  266,  266,
      266,  266,  266,  267,  271,  267,  266,  272,  273,  273,
      266,  266,  274,  275,  266,  269,  269,  269,  266,  276,
      270,  266,  266,  276,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  271,
      271,  272,  273,  273,  273,  273,   84,  272,  273,  272,
      266,  266,  266,  274,  274,  277,  275,  266,  275,  266,

      278,  266,  266,  266,  266,  266,  266,  276,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  272,   90,  273,   87,   84,  266,  266,  266,
      266,  266,  266,  279,  266,  266,  278,  278,  278,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  276,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  266,  266,  266,  266,  266,  266,  279,  279,  266,
      266,  266,  278,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  276,  270,  270,  270,
      270,  270,  270,  270,  270,  266,  266,  266,  266,  266,

      266,  266,  266,  279,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  270,  270,
      270,  270,  270,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  270,  270,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  270,  266,  266,
      266,  266,  266,  266,  266,    0,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266
    } ;

static const flex_int16_t yy_nxt[1007] =
    {   0,
        4,    5,    6,    5,    7,    8,    4,    9,   10,   11,
       12,   13,    9,   14,   15,   16,   17,   18,   19,   19,
       20,   21,   22,   23,   24,   25,   26,    4,   27,   28,
       24,   29,   30,   31,   32,   33,   24,   34,   24,   24,
       24,   24,   35,   36,   24,   24,   37,   38,   39,   40,
       41,   42,   45,   42,   49,   52,   52,   53,   55,   60,
       56,   56,   54,   59,   43,   43,   59,   58,   60,   60,
       60,   60,   50,  139,   46,   62,   58,   62,   63,  139,
       64,   64,  139,   60,   60,   61,   60,   60,  139,   60,
       60,   60,   60,   83,   65,   66,   60,   60,   60,   60,

       45,   67,   69,   60,   60,   42,   68,   42,   74,   70,
       72,   84,   73,   75,   76,   60,   60,   45,   44,   86,
      169,   45,   46,  169,   98,   77,   78,   91,   95,   92,
       92,  100,  100,   79,   45,   96,   93,   87,  101,   81,
       95,   60,   60,   46,   88,   93,  169,  101,   89,   99,
       55,   86,   56,   56,  106,  106,   81,   88,  266,   58,
      266,  266,   63,   98,  105,  105,   90,  134,   58,   88,
       88,   60,   60,  107,   88,   64,   64,   60,   60,   88,
      133,   88,  108,   88,  102,   88,  102,  103,   99,  104,
      104,  108,   99,  109,   60,   60,  110,   60,   60,   60,

       60,   60,   60,   47,   60,   60,  111,   60,   60,   60,
       60,   60,   60,   60,   60,   71,  113,   60,   60,  112,
       86,   60,   60,   60,   60,   60,   60,   86,  114,  115,
      116,   80,   86,  117,   45,   86,   83,   83,   84,  118,
      120,   86,  121,  119,  122,   87,  128,  128,  204,  129,
       87,   92,   92,   87,   84,   87,   81,  123,   93,   84,
      130,   86,  130,  131,   95,  132,  132,   93,   95,   43,
      123,   96,  138,  169,  138,   96,   95,  140,  140,  124,
       95,   51,  123,  123,  139,   51,   91,  123,  135,  135,
      147,  147,  123,  139,  123,  136,  123,  139,  123,  125,

      103,   47,  104,  104,  136,  141,  139,  104,  104,   60,
       60,   43,  125,  107,  142,  105,  105,  144,  266,  145,
      145,  126,  143,  142,  125,  125,  146,   60,   60,  125,
      266,  143,   60,   60,  125,  146,  125,  148,  125,  148,
      125,  123,  149,  149,  150,   83,   60,   60,   60,   60,
      266,  152,   60,   60,  123,   60,   60,   60,   60,   86,
       60,   60,  151,  127,  154,  266,  123,  123,  155,   60,
       60,  123,  157,  156,  153,  266,  123,   87,  123,  196,
      123,  196,  123,   60,   60,   60,   60,   60,   60,  164,
      164,   60,   60,  165,  165,   91,  266,  162,  162,  177,

      177,  266,  160,  131,  163,  132,  132,  181,  181,  266,
      158,  159,  161,  163,  166,  266,  132,  132,  129,  266,
      135,  135,  266,  167,  180,  180,  266,  136,  170,  266,
      170,  171,  167,  172,  172,  173,  136,  173,  178,  174,
      178,  175,  175,  179,  179,   60,   60,  139,  176,  148,
      182,  148,  145,  145,  180,  180,  139,  176,  183,  146,
      183,   60,   60,  184,  184,  149,  149,  144,  146,  185,
      185,  266,  187,   60,   60,  266,  186,   60,   60,   60,
       60,  187,   60,   60,  266,  186,   60,   60,   60,   60,
      266,   60,   60,  188,   60,   60,  189,   60,   60,  266,

       60,   60,  129,  191,  162,  162,  190,  196,  194,  196,
       91,  163,  197,  197,  192,  193,  195,  201,  201,  163,
      163,  198,  266,  199,  199,  205,  205,  202,  163,  202,
      200,  266,  203,  203,  171,  266,  172,  172,  206,  200,
      172,  172,  208,  208,  179,  179,  209,  207,  175,  175,
      216,  216,  210,  266,  210,  176,  207,  211,  211,  174,
      266,  212,  212,  266,  176,  179,  179,  266,  213,  180,
      180,  144,  214,  215,  215,  266,  163,  213,  184,  184,
      163,  214,  266,  184,  184,  163,   60,   60,  266,  163,
      163,  182,  266,  185,  185,  241,  217,  241,  217,  163,

      186,  218,  218,   60,   60,   60,   60,   60,   60,  186,
       60,   60,   60,   60,   60,   60,   60,   60,  129,  266,
      197,  197,  249,  221,  249,  219,  220,  163,  224,  224,
      203,  203,  223,  266,  222,  225,  163,  199,  199,  264,
      226,  264,  226,  266,  200,  227,  227,  198,  266,  228,
      228,  203,  203,  200,  234,  234,  229,  231,  230,  232,
      232,  238,  238,  211,  211,  229,  233,  230,  235,  174,
      235,  237,  237,  236,  236,  233,  211,  211,  214,  209,
      266,  212,  212,  214,  239,  266,  239,  214,  213,  240,
      240,  182,  214,  215,  215,  266,  144,  213,  242,  242,

      163,  218,  218,  218,  218,  163,   60,   60,  266,  163,
      163,   60,   60,  266,  163,   60,   60,   60,   60,  163,
       60,   60,  198,  266,  245,  245,  246,  246,  227,  227,
      266,  230,  266,  243,  227,  227,  225,  244,  228,  228,
      230,  230,  247,  266,  247,  229,  266,  248,  248,  266,
      230,  250,  250,  251,  229,  232,  232,  266,  252,  266,
      252,  266,  233,  253,  253,  231,  266,  254,  254,  236,
      236,  233,  236,  236,  255,  209,  266,  237,  237,  256,
      240,  240,  266,  255,  214,  240,  240,  174,  256,  257,
      257,  266,  214,  214,  266,  182,  214,  242,  242,   60,

       60,  214,   60,   60,  163,  214,  266,  225,  266,  245,
      245,  248,  248,  163,  266,  258,  230,  198,  266,  259,
      259,  248,  248,  261,  261,  230,  230,  231,  230,  260,
      260,  253,  253,  253,  253,  230,  256,  230,  266,  251,
      256,  254,  254,  266,  209,  256,  257,  257,  255,  256,
      262,  266,  262,  214,  266,  263,  263,  255,   60,   60,
      266,  225,  214,  259,  259,  251,  266,  260,  260,  231,
      230,  265,  265,  266,  256,  263,  263,  266,  256,  230,
      266,  263,  263,  256,  266,  266,  266,  256,  256,  251,
      266,  265,  265,  266,  266,  266,  266,  256,  256,  266,

      266,  266,  266,  266,  266,  266,  266,  256,   44,  266,
       44,   44,   44,   48,   48,   48,   57,   57,   80,  266,
       80,   80,   80,   82,   82,   82,   85,   85,   85,   94,
       94,   94,   94,   94,   97,   97,   97,   97,   97,   95,
       95,   95,   95,   95,  137,  266,  137,  137,  137,  168,
      266,  168,  168,  168,    3,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,

      266,  266,  266,  266,  266,  266
    } ;

static const flex_int16_t yy_chk[1007] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    8,    5,   11,   17,   17,   18,   19,  276,
       19,   19,   18,   21,   21,   23,   23,   19,   24,   24,
       29,   29,   11,  137,    8,   25,   19,   25,   25,  138,
       25,   25,  137,   30,   30,  270,   31,   31,  138,   33,
       33,   34,   34,   48,   29,   30,   36,   36,   35,   35,

       44,   30,   31,   37,   37,   42,   30,   42,   34,   31,
       33,   48,   33,   34,   35,   38,   38,   45,   46,   49,
      204,   46,   44,  168,   54,   36,   37,   52,   53,   52,
       52,   55,   55,   38,   80,   53,   52,   49,   55,   45,
       53,   61,   61,   46,   50,   52,  134,   55,   50,   54,
       56,  124,   56,   56,   63,   63,   80,   50,   57,   56,
       57,   57,   62,   97,   62,   62,   50,   99,   56,   50,
       50,   66,   66,   64,   50,   64,   64,   65,   65,   50,
       96,   50,   64,   50,   58,   50,   58,   58,   97,   58,
       58,   64,   99,   65,   67,   67,   66,   68,   68,   69,

       69,   70,   70,   40,   71,   71,   67,   72,   72,   73,
       73,   74,   74,   75,   75,   32,   69,   76,   76,   68,
       82,   77,   77,   78,   78,   79,   79,   83,   70,   71,
       72,   81,   85,   73,   81,   86,   88,   89,   82,   75,
       77,  123,   78,   76,   79,   83,   91,   91,  169,   92,
       85,   92,   92,   86,   88,   89,   81,   84,   92,  123,
       93,   84,   93,   93,   94,   93,   93,   92,   95,   22,
       84,   94,  101,  169,  101,   95,   94,  103,  103,   84,
       95,   16,   84,   84,  101,   14,  100,   84,  100,  100,
      107,  107,   84,  101,   84,  100,   84,  173,   84,   87,

      102,   10,  102,  102,  100,  104,  173,  104,  104,  117,
      117,    7,   87,  105,  104,  105,  105,  106,    3,  106,
      106,   87,  105,  104,   87,   87,  106,  111,  111,   87,
        0,  105,  109,  109,   87,  106,   87,  108,   87,  108,
       87,   90,  108,  108,  109,   90,  110,  110,  112,  112,
        0,  111,  113,  113,   90,  114,  114,  115,  115,  125,
      116,  116,  110,   90,  113,    0,   90,   90,  114,  118,
      118,   90,  116,  115,  112,    0,   90,  125,   90,  163,
       90,  163,   90,  119,  119,  120,  120,  121,  121,  129,
      129,  122,  122,  131,  131,  128,    0,  128,  128,  141,

      141,    0,  121,  130,  128,  130,  130,  144,  144,    0,
      119,  120,  122,  128,  132,    0,  132,  132,  135,    0,
      135,  135,    0,  132,  148,  148,    0,  135,  136,    0,
      136,  136,  132,  136,  136,  139,  135,  139,  142,  140,
      142,  140,  140,  142,  142,  151,  151,  139,  140,  143,
      145,  143,  145,  145,  143,  143,  139,  140,  146,  145,
      146,  152,  152,  146,  146,  149,  149,  147,  145,  147,
      147,    0,  149,  150,  150,    0,  147,  153,  153,  154,
      154,  149,  155,  155,    0,  147,  156,  156,  157,  157,
        0,  158,  158,  150,  159,  159,  153,  160,  160,    0,

      161,  161,  162,  155,  162,  162,  154,  187,  159,  187,
      164,  162,  164,  164,  157,  158,  161,  166,  166,  164,
      162,  165,    0,  165,  165,  171,  171,  167,  164,  167,
      165,    0,  167,  167,  170,    0,  170,  170,  172,  165,
      172,  172,  174,  174,  178,  178,  175,  172,  175,  175,
      182,  182,  176,    0,  176,  175,  172,  176,  176,  177,
        0,  177,  177,    0,  175,  179,  179,    0,  177,  180,
      180,  181,  179,  181,  181,    0,  180,  177,  183,  183,
      181,  179,    0,  184,  184,  180,  188,  188,    0,  181,
      184,  185,    0,  185,  185,  214,  186,  214,  186,  184,

      185,  186,  186,  189,  189,  190,  190,  191,  191,  185,
      192,  192,  193,  193,  194,  194,  195,  195,  197,    0,
      197,  197,  230,  191,  230,  189,  190,  197,  198,  198,
      202,  202,  194,    0,  193,  199,  197,  199,  199,  256,
      200,  256,  200,    0,  199,  200,  200,  201,    0,  201,
      201,  203,  203,  199,  206,  206,  201,  205,  203,  205,
      205,  209,  209,  210,  210,  201,  205,  203,  207,  208,
      207,  208,  208,  207,  207,  205,  211,  211,  208,  212,
        0,  212,  212,  211,  213,    0,  213,  208,  212,  213,
      213,  215,  211,  215,  215,    0,  216,  212,  216,  216,

      215,  217,  217,  218,  218,  216,  219,  219,    0,  215,
      218,  220,  220,    0,  216,  221,  221,  222,  222,  218,
      223,  223,  224,    0,  224,  224,  225,  225,  226,  226,
        0,  224,    0,  219,  227,  227,  228,  220,  228,  228,
      224,  227,  229,    0,  229,  228,    0,  229,  229,    0,
      227,  231,  231,  232,  228,  232,  232,    0,  233,    0,
      233,    0,  232,  233,  233,  234,    0,  234,  234,  235,
      235,  232,  236,  236,  234,  237,    0,  237,  237,  236,
      239,  239,    0,  234,  237,  240,  240,  238,  236,  238,
      238,    0,  240,  237,    0,  242,  238,  242,  242,  243,

      243,  240,  244,  244,  242,  238,    0,  245,    0,  245,
      245,  247,  247,  242,    0,  243,  245,  246,    0,  246,
      246,  248,  248,  251,  251,  245,  246,  250,  248,  250,
      250,  252,  252,  253,  253,  246,  250,  248,    0,  254,
      253,  254,  254,    0,  257,  250,  257,  257,  254,  253,
      255,    0,  255,  257,    0,  255,  255,  254,  258,  258,
        0,  259,  257,  259,  259,  260,    0,  260,  260,  261,
      259,  261,  261,    0,  260,  262,  262,    0,  261,  259,
        0,  263,  263,  260,    0,    0,    0,  261,  263,  265,
        0,  265,  265,    0,    0,    0,    0,  263,  265,    0,

        0,    0,    0,    0,    0,    0,    0,  265,  267,    0,
      267,  267,  267,  268,  268,  268,  269,  269,  271,    0,
      271,  271,  271,  272,  272,  272,  273,  273,  273,  274,
      274,  274,  274,  274,  275,  275,  275,  275,  275,  277,
      277,  277,  277,  277,  278,    0,  278,  278,  278,  279,
        0,  279,  279,  279,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,

      266,  266,  266,  266,  266,  266
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "1705098.l"
#line 4 "1705098.l"
#include<stdio.h>
#include<stdlib.h>
#include<string>
#include<iostream>
#include "1705098_symboltable.h"
using namespace std;


int line=1;
int error_cnt=0;

FILE *logfile = fopen("1705098_log.txt","w");
FILE *tokenfile = fopen("1705098_token.txt","w");

SymbolTable st(7);

void newlines_in_comment(string str){
    for(int i=0;i<str.length();i++){
        if(str[i]=='\n')line++;
    }
}

pair<string,int> manipulate_string(string s){
	int tmp_line = line;
	string x;
	for(int i=1;i<s.size()-1;i++){
		if(s[i]=='\n')line++;
		if(s[i]=='\\' and s[i+1]=='\n') 
		continue;
		int ok=0;
		if(s[i]=='\\' and s[i+1]=='n') 
			x.push_back('\n');
		else if(s[i]=='\\' and s[i+1]=='t') 
			x.push_back('\t');
		else if(s[i]=='\\' and s[i+1]=='\\') 
			x.push_back('\\');
		else if(s[i]=='\\' and s[i+1]=='\'') 
			x.push_back('\'');
		else if(s[i]=='\\' and s[i+1]=='\"') 
			x.push_back('\"');
		else if(s[i]=='\\' and s[i+1]=='a') 
			x.push_back('\a');
		else if(s[i]=='\\' and s[i+1]=='f') 
			x.push_back('\f');
		else if(s[i]=='\\' and s[i+1]=='r') 
			x.push_back('\r');
		else if(s[i]=='\\' and s[i+1]=='v') 
			x.push_back('\v');
		else if(s[i]=='\\' and s[i+1]=='b') 
			x.push_back('\b');
		else if(s[i]=='\\' and s[i+1]=='\0') 
			x.push_back('\0');
		else if(s[i]=='\n' ) 
			continue;
		else{
			ok=1;
			x.push_back(s[i]);
		}
		if(ok==0) i++;
	}
	
	return mp(x , tmp_line); /* returns modified string and starting line cnt*/
} 


#line 822 "test.c"
/*keywords*/
/*operators*/
/* const literals */
/* errors */
/*Too many decimal point error for character sequence like 1.2.345*/
/* ill formed number ex- 11E3.5*/
/*Invalid Suffix on numeric constant or invalid prefix on identifier for character sequence
like 12abcd*/
/*Unfinished character such as ‘a , ‘\n or ‘\’ */
/*Multi character constant error for character sequence like ‘ab’ */
/*unfinished comment*/
/* Rules Section*/
#line 835 "test.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 177 "1705098.l"


#line 1055 "test.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 267 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 955 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 179 "1705098.l"
{}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 181 "1705098.l"
{line++; }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 184 "1705098.l"
{
				int tmp = line;
                newlines_in_comment(yytext);     
                fprintf(logfile,"Line no. %d: Token <COMMENT> Lexeme %s found\n\n",tmp,yytext);      
}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 191 "1705098.l"
{
				int tmp = line;
                newlines_in_comment(yytext); 
                fprintf(logfile,"Line no. %d: Token <COMMENT> Lexeme %s found\n\n",tmp,yytext);          
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 197 "1705098.l"
{
	fprintf(tokenfile,"<CONST_INT,%s> ",yytext);
	fprintf(logfile,"Line no. %d: Token <CONST_INT> Lexeme %s found\n\n",line,yytext);
	bool did = st.Insert(yytext , "CONST_INT",logfile);
    if(did)st.printall(logfile);
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 204 "1705098.l"
{
	fprintf(tokenfile,"<CONST_FLOAT,%s> ",yytext);
	fprintf(logfile,"Line no. %d: Token <CONST_FLOAT> Lexeme %s found\n\n",line,yytext);
	bool did = st.Insert(yytext , "CONST_FLOAT",logfile);
	if(did)st.printall(logfile);
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 212 "1705098.l"
{
	string str = yytext;
    if(str.length()==3){
		fprintf(logfile,"Line no. %d: Token <CONST_CHAR> Lexeme %s found --> <CHAR_CONST,%c>\n",line,yytext,str[1]);
		fprintf(tokenfile,"<CONST_CHAR,%c> ",str[1]);
	}
	else {
		
		char ch;
		if(str[2]=='n')ch='\n';
		else if(str[2]=='t')ch='\t';
		else if(str[2]=='a')ch='\a';
		else if(str[2]=='f')ch='\f';
		else if(str[2]=='r')ch='\r';
		else if(str[2]=='b')ch='\b';
		else if(str[2]=='v')ch='\v';
		else if(str[2]=='0')ch='\0';
		else if(str[2]=='\'')ch='\'';
		else if(str[2]=='\"')ch='\"';
		fprintf(tokenfile,"<CONST_CHAR,%c> ",ch);
		fprintf(logfile,"Line no. %d: Token <CONST_CHAR> Lexeme %s found --> <CHAR_CONST,%c>\n",line,yytext,ch);
	}
	bool did = st.Insert(yytext , "CONST_CHAR",logfile);
    if(did)st.printall(logfile);
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 238 "1705098.l"
{
	fprintf(tokenfile,"<BREAK> ");
	fprintf(logfile,"Line no. %d: Token <BREAK> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 243 "1705098.l"
{
	fprintf(tokenfile,"<CASE> ");
	fprintf(logfile,"Line no. %d: Token <CASE> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 248 "1705098.l"
{
	fprintf(tokenfile,"<CHAR> ");
	fprintf(logfile,"Line no. %d: Token <CHAR> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 253 "1705098.l"
{
	fprintf(tokenfile,"<CONTINUE> ");
	fprintf(logfile,"Line no. %d: Token <CONTINUE> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 258 "1705098.l"
{
	fprintf(tokenfile,"<DEFAULT> ");
	fprintf(logfile,"Line no. %d: Token <DEFAULT> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 263 "1705098.l"
{
	fprintf(tokenfile,"<DO> ");
	fprintf(logfile,"Line no. %d: Token <DO> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 268 "1705098.l"
{
	fprintf(tokenfile,"<DOUBLE> ");
	fprintf(logfile,"Line no. %d: Token <DOUBLE> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 273 "1705098.l"
{
	fprintf(tokenfile,"<ELSE> ");
	fprintf(logfile,"Line no. %d: Token <ELSE> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 278 "1705098.l"
{
	fprintf(tokenfile,"<FLOAT> ");
	fprintf(logfile,"Line no. %d: Token <FLOAT> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 283 "1705098.l"
{
	fprintf(tokenfile,"<FOR> ");
	fprintf(logfile,"Line no. %d: Token <FOR> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 288 "1705098.l"
{
	fprintf(tokenfile,"<IF> ");
	fprintf(logfile,"Line no. %d: Token <IF> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 293 "1705098.l"
{
	fprintf(tokenfile,"<INT> ");
	fprintf(logfile,"Line no. %d: Token <INT> Lexeme %s found\n\n",line,yytext);

}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 299 "1705098.l"
{
	fprintf(tokenfile,"<RETURN> ");
	fprintf(logfile,"Line no. %d: Token <RETURN> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 304 "1705098.l"
{
	fprintf(tokenfile,"<SWITCH> ");
	fprintf(logfile,"Line no. %d: Token <SWITCH> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 309 "1705098.l"
{
	fprintf(tokenfile,"<WHILE> ");
	fprintf(logfile,"Line no. %d: Token <WHILE> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 314 "1705098.l"
{
	fprintf(tokenfile,"<VOID> ");
	fprintf(logfile,"Line no. %d: Token <VOID> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 319 "1705098.l"
{
	fprintf(tokenfile,"<ADDOP,%s> ",yytext);
	fprintf(logfile,"Line no. %d: Token <ADDOP> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 324 "1705098.l"
{
	fprintf(tokenfile,"<MULOP,%s> ",yytext);
	fprintf(logfile,"Line no. %d: Token <MULOP> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 329 "1705098.l"
{
	fprintf(tokenfile,"<RELOP,%s> ",yytext);
	fprintf(logfile,"Line no. %d: Token <RELOP> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 334 "1705098.l"
{
	fprintf(tokenfile,"<INCOP,%s> ",yytext);
	fprintf(logfile,"Line no. %d: Token <INCOP> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 339 "1705098.l"
{
	fprintf(tokenfile,"<LOGICOP,%s> ",yytext);
	fprintf(logfile,"Line no. %d: Token <LOGICOP> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 344 "1705098.l"
{
	fprintf(tokenfile,"<BITOP,%s> ",yytext);
	fprintf(logfile,"Line no. %d: Token <BITOP> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 349 "1705098.l"
{
	fprintf(tokenfile,"<ASSIGNOP,%s> ",yytext);
	fprintf(logfile,"Line no. %d: Token <ASSIGNOP> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 354 "1705098.l"
{
	fprintf(tokenfile,"<NOT,%s> ",yytext);
	fprintf(logfile,"Line no. %d: Token <NOT> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 359 "1705098.l"
{
	fprintf(tokenfile,"<LPAREN,%s> ",yytext);
	fprintf(logfile,"Line no. %d: Token <LPAREN> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 364 "1705098.l"
{
	fprintf(tokenfile,"<RPAREN,%s> ",yytext);
	fprintf(logfile,"Line no. %d: Token <RPAREN> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 369 "1705098.l"
{
	fprintf(tokenfile,"<LCURL,%s> ",yytext);
	fprintf(logfile,"Line no. %d: Token <LCURL> Lexeme %s found\n\n",line,yytext);
	st.Enter_Scope();
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 375 "1705098.l"
{
	fprintf(tokenfile,"<RCURL,%s> ",yytext);
	fprintf(logfile,"Line no. %d: Token <RCURL> Lexeme %s found\n\n",line,yytext);
	st.Exit_Scope();
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 381 "1705098.l"
{
	fprintf(tokenfile,"<LTHIRD,%s> ",yytext);
	fprintf(logfile,"Line no. %d: Token <LTHIRD> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 386 "1705098.l"
{
	fprintf(tokenfile,"<RTHIRD,%s> ",yytext);
	fprintf(logfile,"Line no. %d: Token <RTHIRD> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 391 "1705098.l"
{
	fprintf(tokenfile,"<COMMA,%s> ",yytext);
	fprintf(logfile,"Line no. %d: Token <COMMA> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 396 "1705098.l"
{
	fprintf(tokenfile,"<SEMICOLON,%s> ",yytext);
	fprintf(logfile,"Line no. %d: Token <SEMICOLON> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 401 "1705098.l"
{
	fprintf(tokenfile,"<ID,%s> ",yytext);
	fprintf(logfile,"Line no. %d: Token <ID> Lexeme %s found\n\n",line,yytext);
	bool did = st.Insert(yytext , "ID" , logfile);
	if(did)st.printall(logfile);
}
	YY_BREAK
case 41:
/* rule 41 can match eol */
YY_RULE_SETUP
#line 408 "1705098.l"
{
	pair<string , int> processed = manipulate_string(yytext);
	fprintf(logfile,"Line no. %d: Token <STRING> Lexeme %s found --> <STRING , %s>\n",processed.second,yytext,processed.first.c_str());
	fprintf(tokenfile,"<STRING,%s> ",processed.first.c_str());
	
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 415 "1705098.l"
{
	error_cnt++;
	fprintf(logfile,"Error at line. %d: Too many decimal points %s\n\n",line,yytext);
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 420 "1705098.l"
{
	error_cnt++;
	fprintf(logfile,"Error at line. %d: Ill formed numer: %s\n\n",line,yytext);
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 425 "1705098.l"
{
	error_cnt++;
	fprintf(logfile,"Error at line. %d: Invalid prefix on ID or invalid suffix on Number %s\n\n",line,yytext);
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 430 "1705098.l"
{
	error_cnt++;
	fprintf(logfile,"Error at line. %d: Empty character constant error %s\n\n",line,yytext);
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 435 "1705098.l"
{
	error_cnt++;
	fprintf(logfile,"Error at line. %d: Unterminated character %s\n\n",line,yytext);
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 440 "1705098.l"
{
	error_cnt++;
	fprintf(logfile,"Error at line. %d: Multi character constant error %s\n\n",line,yytext);
}
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 445 "1705098.l"
{
	error_cnt++;
	int tmp = line;
    newlines_in_comment(yytext); 
	fprintf(logfile,"Error at line. %d: Unterminated comment %s\n\n",tmp,yytext);
}
	YY_BREAK
case 49:
/* rule 49 can match eol */
YY_RULE_SETUP
#line 452 "1705098.l"
{
	error_cnt++;
	int tmp = line;
	pair<string , int> p = manipulate_string(yytext);
	fprintf(logfile,"Error at line. %d: Unterminated string %s\n\n",tmp,yytext);
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 459 "1705098.l"
{
	error_cnt++;
	fprintf(logfile,"Error at line. %d: Unrecgnized character %s\n\n",line,yytext);
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 463 "1705098.l"
ECHO;
	YY_BREAK
#line 1555 "test.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 267 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 267 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 266);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 463 "1705098.l"


int main(int argc,char *argv[]){
	
	if(argc!=2){
		printf("Please provide input file name and try again\n");
		return 0;
	}
	
	FILE *fin=fopen(argv[1],"r");
	if(fin==NULL){
		printf("Cannot open specified file\n");
		return 0;
	}
	
	
	yyin= fin;
	yylex();
    st.printall(logfile);
	fprintf(logfile,"\nTotal Lines : %d\nTotal Errors : %d\n",line,error_cnt);
	fclose(yyin);
	fclose(tokenfile);
	fclose(logfile);
	return 0;
}


