#line 2 "test.c"

#line 4 "test.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 51
#define YY_END_OF_BUFFER 52
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[271] =
    {   0,
       44,   44,    0,    0,   52,   50,    1,    2,   31,   49,
       25,   29,   46,   32,   33,   24,   38,   24,   50,   25,
        5,   39,   26,   30,   26,   50,   40,   40,   36,   37,
       29,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   34,   29,   35,   51,    1,   26,   49,   41,   49,
       28,   46,   45,    0,   27,    6,    0,    4,   43,    5,
       44,   43,   29,   40,   40,    0,    0,   40,   40,   40,
       40,   40,   40,   13,   40,   40,   40,   18,   40,   40,
       40,   40,   40,    0,    0,   46,    7,    0,    0,   47,
        0,   46,   46,   46,    0,    6,   43,   48,    0,    0,

        4,    3,    4,    6,   43,   43,    0,    6,   43,   43,
        0,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       17,   19,   40,   40,   40,   40,   46,   46,    0,    0,
        0,   42,    0,   43,    0,    6,    4,    3,    6,   43,
       43,   43,   43,   43,    0,   43,   43,    0,   43,   43,
       43,   43,   40,   40,    9,   10,   40,   40,   40,   15,
       40,   40,   40,   23,   40,   42,   43,   42,   43,    0,
       43,    4,    4,   43,    0,    6,   43,    0,   43,   43,
       43,   43,   43,   43,   43,    0,   43,   43,   43,   43,
       40,    8,   40,   40,   40,   16,   40,   40,   22,   43,

       42,    0,   43,   43,   43,   43,   43,    4,   43,    0,
       43,   43,    0,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   40,   40,   14,   20,   21,   43,    0,   43,
       43,   43,   43,   43,    0,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   40,   12,   43,   43,
       43,   43,   43,   43,    0,   43,   43,   43,   43,   43,
       43,   11,   43,   43,   43,   43,   43,   43,   43,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,    7,   21,   22,
       23,   24,    7,   25,   26,   26,   26,   26,   27,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       28,   29,   30,   31,   26,   32,   33,   34,   35,   36,

       37,   38,   26,   39,   40,   26,   41,   42,   26,   43,
       44,   26,   26,   45,   46,   47,   48,   49,   50,   26,
       26,   26,   51,   52,   53,    7,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[54] =
    {   0,
        1,    1,    2,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    4,    3,    5,    5,
        3,    3,    3,    3,    3,    5,    5,    3,    3,    3,
        3,    3,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        3,    3,    3
    } ;

static const flex_int16_t yy_base[285] =
    {   0,
        0,    0,    0,    0,  299,  968,   52,  968,  268,   49,
      968,  278,   47,  968,  968,  265,  968,  258,   39,   47,
       44,  968,   44,  236,   45,  968,   53,   63,  968,  968,
      968,   55,   65,   68,  204,   71,   73,   77,   75,   82,
       88,  968,  186,  968,  968,  115,  968,   93,  100,  115,
      968,   60,  110,  139,  968,  111,  128,  107,  113,  134,
      140,  150,  968,    0,  104,  159,  123,  170,  143,  155,
      172,  174,  176,  179,  183,  189,  136,  191,  193,  196,
      199,  201,  204,  177,  219,  175,  216,  243,  218,  221,
      287,  222,  225,  331,  217,  238,  247,  265,  267,  182,

      227,  968,  231,  277,  268,  281,  249,  290,  325,  329,
      283,  299,  320,  292,  338,  304,  335,  351,  353,  362,
      367,  369,  372,  374,  377,  380,  260,  155,  318,    0,
        0,  387,  382,  391,  396,  406,  968,  123,  410,  422,
      110,  215,  418,  429,  398,  438,  445,  431,  443,  453,
      457,  459,  462,  466,  468,  471,  473,  476,  478,  481,
      483,  486,  490,  492,  495,  499,  317,  518,  522,  502,
      532,  106,  332,  537,  508,  541,  340,  514,  545,  555,
      560,  524,  564,  566,  575,  547,  569,  579,  588,  603,
      389,  590,  594,  601,  607,  609,  611,  613,  615,  968,

      619,  621,  628,  643,  641,  630,  647,   74,  652,  656,
      666,  671,  673,  675,  677,  682,  691,  637,  696,  701,
      705,  707,  710,  712,  716,  720,  722,  726,  728,  730,
      735,  747,  757,  667,  732,  761,  771,  775,  737,  777,
      786,  790,  741,  781,  968,  802,  749,  763,  811,  815,
      796,  806,  968,  827,  817,  821,  830,  836,  846,  845,
      851,  855,  860,  864,  873,  866,  875,  968,  879,  968,
      916,  921,  924,  926,   81,  931,  934,  937,  942,  947,
       57,  952,  957,  962
    } ;

static const flex_int16_t yy_def[285] =
    {   0,
      270,    1,  271,  271,  270,  270,  270,  270,  270,  272,
      270,  270,  273,  270,  270,  270,  270,  270,  270,  270,
      274,  270,  270,  270,  270,  270,  275,  275,  270,  270,
      270,  275,  275,  275,   28,  275,  275,  275,  275,  275,
      275,  270,  270,  270,  270,  270,  270,  272,  276,  272,
      270,  277,  278,  278,  270,  270,  279,  280,  270,  274,
      274,  274,  270,  281,  275,  270,  270,  281,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  276,  276,  277,  278,  278,  278,  278,
       88,  277,  278,  277,  270,  270,  270,  279,  279,  282,

      280,  270,  280,  270,  283,  270,  270,  270,  270,  270,
      270,  281,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  277,   94,  278,   91,
       88,  270,  270,  270,  270,  270,  270,  284,  270,  270,
      283,  283,  283,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  281,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  270,  270,  270,  270,  270,
      270,  284,  284,  270,  270,  270,  283,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      281,  275,  275,  275,  275,  275,  275,  275,  275,  270,

      270,  270,  270,  270,  270,  270,  270,  284,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  275,  275,  275,  275,  275,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  275,  275,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  275,  270,  270,  270,  270,  270,  270,  270,    0,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270
    } ;

static const flex_int16_t yy_nxt[1022] =
    {   0,
        6,    7,    8,    7,    9,   10,    6,   11,   12,   13,
       14,   15,   11,   16,   17,   18,   19,   20,   21,   21,
       22,   23,   24,   25,   26,   27,   28,   29,    6,   30,
       31,   26,   27,   32,   33,   34,   35,   36,   27,   37,
       27,   27,   27,   27,   38,   39,   27,   27,   40,   41,
       42,   43,   44,   46,   49,   46,   53,   56,   56,   57,
       59,   64,   60,   60,   58,   63,   47,   47,   63,   87,
       62,   64,   64,   64,   64,   54,   66,   50,   66,   67,
       62,   68,   68,   64,   64,   65,   64,   64,   88,   64,
       64,   64,   64,   64,   64,   64,   64,   70,   49,   69,

       64,   64,  173,   71,   73,   49,   64,   64,   72,  102,
       78,   74,   76,   80,   77,   79,   46,   48,   46,   90,
       49,   50,   64,   64,   81,   82,   83,   95,   85,   96,
       96,  104,  104,   99,  173,  103,  143,   97,   91,  105,
      100,  110,  110,   50,   92,   99,  143,   97,   93,  105,
       59,  173,   60,   60,   64,   64,  270,   92,  270,  270,
       62,   64,   64,  106,   90,  106,  107,   94,  108,  108,
       62,   92,   92,   64,   64,   67,   92,  109,  109,  113,
      121,   92,   49,   92,   90,   92,  111,   92,   68,   68,
       64,   64,   64,   64,   64,   64,  112,   64,   64,  137,

      114,   64,   64,   88,  115,   85,  112,   64,   64,   64,
       64,   64,   64,  117,   64,   64,  116,   64,   64,   64,
       64,   84,   64,   64,   49,   90,  118,   90,  119,  102,
       90,   87,  120,  138,   87,  132,  132,   51,  124,  122,
      125,  143,  123,  126,   91,   75,   91,   85,  127,   91,
       88,  143,   90,   91,  133,  103,   96,   96,   47,  103,
      134,  127,  134,  135,   97,  136,  136,  144,  144,   90,
       99,  128,   99,   55,   97,  127,  127,  100,   55,  100,
      127,  142,   99,  142,   99,  127,   51,  127,   88,  127,
       47,  127,  129,   95,  143,  139,  139,  107,  270,  108,

      108,  151,  151,  140,  143,  129,  145,  270,  108,  108,
       64,   64,  152,  140,  152,  130,  146,  153,  153,  129,
      129,  270,   64,   64,  129,  270,  146,   90,  155,  129,
      200,  129,  200,  129,  208,  129,  127,  270,   64,   64,
       87,  111,  270,  109,  109,  148,   91,  149,  149,  127,
      157,  147,  154,   64,   64,  150,   64,   64,  270,  131,
      173,  147,  270,  127,  127,  150,  143,  158,  127,   64,
       64,   64,   64,  127,  270,  127,  143,  127,  270,  127,
       64,   64,  156,  270,  159,   64,   64,   64,   64,  160,
       64,   64,   64,   64,  161,   64,   64,  270,   64,   64,

      168,  168,  200,   95,  200,  166,  166,  135,  270,  136,
      136,  270,  164,  167,  169,  169,  181,  181,  270,  162,
      163,  165,  170,  167,  136,  136,  133,  270,  139,  139,
      270,  177,  171,  177,  270,  174,  140,  174,  175,  270,
      176,  176,  171,  270,  143,  178,  140,  179,  179,  185,
      185,  182,  270,  182,  143,  180,  183,  183,  152,  186,
      152,  149,  149,  184,  184,  180,  187,  270,  187,  150,
      270,  188,  188,  148,  270,  189,  189,  184,  184,  150,
      153,  153,  270,  190,   64,   64,   64,   64,  191,   64,
       64,   64,   64,  190,   64,   64,   64,   64,  191,   64,

       64,   64,   64,  270,   64,   64,  192,  270,   64,   64,
       64,   64,  193,   64,   64,  133,  270,  166,  166,  195,
      205,  205,  270,  194,  198,  167,  209,  209,  270,  196,
      197,  199,  212,  212,   95,  167,  201,  201,  202,  270,
      203,  203,  183,  183,  167,  206,  270,  206,  204,  270,
      207,  207,  270,  175,  167,  176,  176,  210,  204,  176,
      176,  213,  270,  179,  179,  220,  220,  211,  214,  270,
      214,  180,  270,  215,  215,  270,  178,  211,  216,  216,
      270,  180,  183,  183,  184,  184,  217,  188,  188,  270,
      218,  148,  167,  219,  219,  270,  217,  188,  188,  270,

      218,  167,  167,  270,  186,  167,  189,  189,   64,   64,
      270,  167,   64,   64,  190,  167,  221,  270,  221,   64,
       64,  222,  222,  270,  190,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,  133,  223,  201,  201,  228,
      228,  270,  224,  225,  229,  167,  203,  203,  207,  207,
      245,  227,  245,  226,  204,  167,  230,  202,  230,  232,
      232,  231,  231,  270,  204,  207,  207,  233,  235,  270,
      236,  236,  270,  234,  238,  238,  270,  233,  237,  239,
      253,  239,  253,  234,  240,  240,  270,  178,  237,  241,
      241,  242,  242,  215,  215,  215,  215,  218,  213,  270,

      216,  216,  270,  218,  243,  270,  243,  218,  217,  244,
      244,  270,  186,  218,  219,  219,  270,  148,  217,  246,
      246,  270,  167,  222,  222,  222,  222,  167,   64,   64,
       64,   64,  167,  167,   64,   64,  270,  167,   64,   64,
       64,   64,  202,  167,  249,  249,  250,  250,  231,  231,
      254,  254,  234,  231,  231,  240,  240,  247,  248,  244,
      244,  234,  234,  229,  270,  232,  232,   64,   64,  270,
      251,  234,  251,  233,  270,  252,  252,  255,  270,  236,
      236,   64,   64,  233,  256,  262,  256,  237,  270,  257,
      257,  235,  270,  258,  258,  240,  240,  237,  270,  244,

      244,  259,  213,  260,  241,  241,  178,  218,  261,  261,
      270,  259,  218,  260,  252,  252,  218,  218,  186,  270,
      246,  246,  218,  270,  252,  252,  218,  229,  167,  249,
      249,  202,  234,  263,  263,  265,  265,  234,  167,  257,
      257,  234,  234,  235,  270,  264,  264,  234,  257,  257,
      270,  234,  255,  260,  258,  258,  260,  270,  268,  266,
      268,  266,  259,  260,  267,  267,  260,  213,  270,  261,
      261,  270,  259,   64,   64,  270,  229,  218,  263,  263,
      255,  270,  264,  264,  267,  267,  234,  218,  270,  235,
      260,  269,  269,  267,  267,  255,  234,  269,  269,  260,

      260,  260,  270,  270,  270,  260,  270,  270,  270,  260,
      270,  260,  270,  270,  270,  260,   45,   45,   45,   45,
       45,   48,  270,   48,   48,   48,   52,   52,   52,   61,
       61,   84,  270,   84,   84,   84,   86,   86,   86,   89,
       89,   89,   98,   98,   98,   98,   98,  101,  101,  101,
      101,  101,   99,   99,   99,   99,   99,  141,  270,  141,
      141,  141,  172,  270,  172,  172,  172,    5,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,

      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270
    } ;

static const flex_int16_t yy_chk[1022] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    7,   10,    7,   13,   19,   19,   20,
       21,  281,   21,   21,   20,   23,   23,   25,   25,   52,
       21,   27,   27,   32,   32,   13,   28,   10,   28,   28,
       21,   28,   28,   33,   33,  275,   34,   34,   52,   36,
       36,   37,   37,   39,   39,   38,   38,   33,   48,   32,

       40,   40,  208,   33,   34,   49,   41,   41,   33,   58,
       37,   34,   36,   38,   36,   37,   46,   50,   46,   53,
       50,   48,   65,   65,   39,   40,   41,   56,   49,   56,
       56,   59,   59,   57,  172,   58,  141,   56,   53,   59,
       57,   67,   67,   50,   54,   57,  141,   56,   54,   59,
       60,  138,   60,   60,   77,   77,   61,   54,   61,   61,
       60,   69,   69,   62,  128,   62,   62,   54,   62,   62,
       60,   54,   54,   70,   70,   66,   54,   66,   66,   69,
       77,   54,   84,   54,   86,   54,   68,   54,   68,   68,
       71,   71,   72,   72,   73,   73,   68,   74,   74,  100,

       70,   75,   75,   86,   71,   84,   68,   76,   76,   78,
       78,   79,   79,   73,   80,   80,   72,   81,   81,   82,
       82,   85,   83,   83,   85,   87,   74,   89,   75,  101,
       90,   92,   76,  103,   93,   95,   95,   43,   81,   79,
       82,  142,   80,   83,   87,   35,   89,   85,   88,   90,
       92,  142,   88,   93,   96,  101,   96,   96,   24,  103,
       97,   88,   97,   97,   96,   97,   97,  107,  107,  127,
       98,   88,   99,   18,   96,   88,   88,   98,   16,   99,
       88,  105,   98,  105,   99,   88,   12,   88,  127,   88,
        9,   88,   91,  104,  105,  104,  104,  106,    5,  106,

      106,  111,  111,  104,  105,   91,  108,    0,  108,  108,
      114,  114,  112,  104,  112,   91,  108,  112,  112,   91,
       91,    0,  116,  116,   91,    0,  108,  129,  114,   91,
      167,   91,  167,   91,  173,   91,   94,    0,  113,  113,
       94,  109,    0,  109,  109,  110,  129,  110,  110,   94,
      116,  109,  113,  117,  117,  110,  115,  115,    0,   94,
      173,  109,    0,   94,   94,  110,  177,  117,   94,  118,
      118,  119,  119,   94,    0,   94,  177,   94,    0,   94,
      120,  120,  115,    0,  118,  121,  121,  122,  122,  119,
      123,  123,  124,  124,  120,  125,  125,    0,  126,  126,

      133,  133,  191,  132,  191,  132,  132,  134,    0,  134,
      134,    0,  125,  132,  135,  135,  145,  145,    0,  123,
      124,  126,  136,  132,  136,  136,  139,    0,  139,  139,
        0,  143,  136,  143,    0,  140,  139,  140,  140,    0,
      140,  140,  136,    0,  143,  144,  139,  144,  144,  148,
      148,  146,    0,  146,  143,  144,  146,  146,  147,  149,
      147,  149,  149,  147,  147,  144,  150,    0,  150,  149,
        0,  150,  150,  151,    0,  151,  151,  152,  152,  149,
      153,  153,    0,  151,  154,  154,  155,  155,  153,  156,
      156,  157,  157,  151,  158,  158,  159,  159,  153,  160,

      160,  161,  161,    0,  162,  162,  154,    0,  163,  163,
      164,  164,  157,  165,  165,  166,    0,  166,  166,  159,
      170,  170,    0,  158,  163,  166,  175,  175,    0,  161,
      162,  165,  178,  178,  168,  166,  168,  168,  169,    0,
      169,  169,  182,  182,  168,  171,    0,  171,  169,    0,
      171,  171,    0,  174,  168,  174,  174,  176,  169,  176,
      176,  179,    0,  179,  179,  186,  186,  176,  180,    0,
      180,  179,    0,  180,  180,    0,  181,  176,  181,  181,
        0,  179,  183,  183,  184,  184,  181,  187,  187,    0,
      183,  185,  184,  185,  185,    0,  181,  188,  188,    0,

      183,  185,  184,    0,  189,  188,  189,  189,  192,  192,
        0,  185,  193,  193,  189,  188,  190,    0,  190,  194,
      194,  190,  190,    0,  189,  195,  195,  196,  196,  197,
      197,  198,  198,  199,  199,  201,  193,  201,  201,  202,
      202,    0,  194,  195,  203,  201,  203,  203,  206,  206,
      218,  198,  218,  197,  203,  201,  204,  205,  204,  205,
      205,  204,  204,    0,  203,  207,  207,  205,  209,    0,
      209,  209,    0,  207,  210,  210,    0,  205,  209,  211,
      234,  211,  234,  207,  211,  211,    0,  212,  209,  212,
      212,  213,  213,  214,  214,  215,  215,  212,  216,    0,

      216,  216,    0,  215,  217,    0,  217,  212,  216,  217,
      217,    0,  219,  215,  219,  219,    0,  220,  216,  220,
      220,    0,  219,  221,  221,  222,  222,  220,  223,  223,
      224,  224,  219,  222,  225,  225,    0,  220,  226,  226,
      227,  227,  228,  222,  228,  228,  229,  229,  230,  230,
      235,  235,  228,  231,  231,  239,  239,  223,  224,  243,
      243,  231,  228,  232,    0,  232,  232,  247,  247,    0,
      233,  231,  233,  232,    0,  233,  233,  236,    0,  236,
      236,  248,  248,  232,  237,  247,  237,  236,    0,  237,
      237,  238,    0,  238,  238,  240,  240,  236,    0,  244,

      244,  238,  241,  240,  241,  241,  242,  244,  242,  242,
        0,  238,  241,  240,  251,  251,  242,  244,  246,    0,
      246,  246,  241,    0,  252,  252,  242,  249,  246,  249,
      249,  250,  252,  250,  250,  255,  255,  249,  246,  256,
      256,  250,  252,  254,    0,  254,  254,  249,  257,  257,
        0,  250,  258,  254,  258,  258,  257,    0,  260,  259,
      260,  259,  258,  254,  259,  259,  257,  261,    0,  261,
      261,    0,  258,  262,  262,    0,  263,  261,  263,  263,
      264,    0,  264,  264,  266,  266,  263,  261,    0,  265,
      264,  265,  265,  267,  267,  269,  263,  269,  269,  265,

      264,  267,    0,    0,    0,  269,    0,    0,    0,  265,
        0,  267,    0,    0,    0,  269,  271,  271,  271,  271,
      271,  272,    0,  272,  272,  272,  273,  273,  273,  274,
      274,  276,    0,  276,  276,  276,  277,  277,  277,  278,
      278,  278,  279,  279,  279,  279,  279,  280,  280,  280,
      280,  280,  282,  282,  282,  282,  282,  283,    0,  283,
      283,  283,  284,    0,  284,  284,  284,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,

      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "1705098.l"

#line 6 "1705098.l"
#include<stdio.h>
#include<stdlib.h>
#include<string>
#include<iostream>
#include "1705098_symboltable.h"
using namespace std;


int line=1;
int error_cnt=0;

FILE *logfile = fopen("1705098_log.txt","w");
FILE *tokenfile = fopen("1705098_token.txt","w");

SymbolTable st(7);

void newlines_in_comment(string str){
    for(int i=0;i<str.length();i++){
        if(str[i]=='\n')line++;
    }
}

pair<string,int> manipulate_string(string s){
	int tmp_line = line;
	string x;
	for(int i=1;i<s.size()-1;i++){
		if(s[i]=='\n')line++;
		if(s[i]=='\\' and s[i+1]=='\n') 
		continue;
		int ok=0;
		if(s[i]=='\\' and s[i+1]=='n') 
			x.push_back('\n');
		else if(s[i]=='\\' and s[i+1]=='t') 
			x.push_back('\t');
		else if(s[i]=='\\' and s[i+1]=='\\') 
			x.push_back('\\');
		else if(s[i]=='\\' and s[i+1]=='\'') 
			x.push_back('\'');
		else if(s[i]=='\\' and s[i+1]=='\"') 
			x.push_back('\"');
		else if(s[i]=='\\' and s[i+1]=='a') 
			x.push_back('\a');
		else if(s[i]=='\\' and s[i+1]=='f') 
			x.push_back('\f');
		else if(s[i]=='\\' and s[i+1]=='r') 
			x.push_back('\r');
		else if(s[i]=='\\' and s[i+1]=='v') 
			x.push_back('\v');
		else if(s[i]=='\\' and s[i+1]=='b') 
			x.push_back('\b');
		else if(s[i]=='\\' and s[i+1]=='\0') 
			x.push_back('\0');
		else if(s[i]=='\n' ) 
			continue;
		else{
			ok=1;
			x.push_back(s[i]);
		}
		if(ok==0) i++;
	}
	
	return mp(x , tmp_line); /* returns modified string and starting line cnt*/
} 


#line 829 "test.c"
/*keywords*/
/*operators*/
/* need to be modified*/
/*FLOAT_LITERAL {DIGIT}*\.{DIGIT}+([E][-+]?{DIGIT}+)? | {DIGIT}+([E][-+]?{DIGIT}+)?*/
/* const literals */
/* errors */
/*Too many decimal point error for character sequence like 1.2.345*/
/* ill formed number ex- 11E3.5*/
/*Invalid Suffix on numeric constant or invalid prefix on identifier for character sequence
like 12abcd*/
/*Unfinished character such as ‘a , ‘\n or ‘\’ */
/*Multi character constant error for character sequence like ‘ab’ */
/*unfinished comment*/
/*unfinished string*/
/*unrecognized char*/
/* Rules Section*/
#line 846 "test.c"

#define INITIAL 0
#define fnd_multiline_comment 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 188 "1705098.l"


#line 1067 "test.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 271 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 968 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 190 "1705098.l"
{}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 192 "1705098.l"
{line++; }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 195 "1705098.l"
{
				int tmp = line;
                newlines_in_comment(yytext);     
                fprintf(logfile,"Line no. %d: Token <COMMENT> Lexeme %s found\n\n",tmp,yytext);      
}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 202 "1705098.l"
{
				int tmp = line;
                newlines_in_comment(yytext); 
                fprintf(logfile,"Line no. %d: Token <COMMENT> Lexeme %s found\n\n",tmp,yytext);          
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 208 "1705098.l"
{
	fprintf(tokenfile,"<CONST_INT,%s>",yytext);
	fprintf(logfile,"Line no. %d: Token <CONST_INT> Lexeme %s found\n\n",line,yytext);
	bool did = st.Insert(yytext , "CONST_INT",logfile);
    if(did)st.printall(logfile);
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 215 "1705098.l"
{
	fprintf(tokenfile,"<CONST_FLOAT,%s>",yytext);
	fprintf(logfile,"Line no. %d: Token <CONST_FLOAT> Lexeme %s found\n\n",line,yytext);
	bool did = st.Insert(yytext , "CONST_FLOAT",logfile);
	if(did)st.printall(logfile);
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 223 "1705098.l"
{
	string str = yytext;
    if(str.length()==3){
		fprintf(logfile,"Line no. %d: Token <CONST_CHAR> Lexeme %s found --> <CHAR_CONST,%c>\n",line,yytext,str[1]);
		fprintf(tokenfile,"<CONST_CHAR,%c>",str[1]);
	}
	else {
		
		char ch;
		if(str[2]=='n')ch='\n';
		else if(str[2]=='t')ch='\t';
		else if(str[2]=='a')ch='\a';
		else if(str[2]=='f')ch='\f';
		else if(str[2]=='r')ch='\r';
		else if(str[2]=='b')ch='\b';
		else if(str[2]=='v')ch='\v';
		else if(str[2]=='0')ch='\0';
		else if(str[2]=='\'')ch='\'';
		else if(str[2]=='\"')ch='\"';
		fprintf(tokenfile,"<CONST_CHAR,%c>",ch);
		fprintf(logfile,"Line no. %d: Token <CONST_CHAR> Lexeme %s found --> <CHAR_CONST,%c>\n",line,yytext,ch);
	}
	bool did = st.Insert(yytext , "CONST_CHAR",logfile);
    if(did)st.printall(logfile);
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 249 "1705098.l"
{
	fprintf(tokenfile,"<BREAK>");
	fprintf(logfile,"Line no. %d: Token <BREAK> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 254 "1705098.l"
{
	fprintf(tokenfile,"<CASE>");
	fprintf(logfile,"Line no. %d: Token <CASE> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 259 "1705098.l"
{
	fprintf(tokenfile,"<CHAR>");
	fprintf(logfile,"Line no. %d: Token <CHAR> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 264 "1705098.l"
{
	fprintf(tokenfile,"<CONTINUE>");
	fprintf(logfile,"Line no. %d: Token <CONTINUE> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 269 "1705098.l"
{
	fprintf(tokenfile,"<DEFAULT>");
	fprintf(logfile,"Line no. %d: Token <DEFAULT> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 274 "1705098.l"
{
	fprintf(tokenfile,"<DO>");
	fprintf(logfile,"Line no. %d: Token <DO> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 279 "1705098.l"
{
	fprintf(tokenfile,"<DOUBLE>");
	fprintf(logfile,"Line no. %d: Token <DOUBLE> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 284 "1705098.l"
{
	fprintf(tokenfile,"<ELSE>");
	fprintf(logfile,"Line no. %d: Token <ELSE> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 289 "1705098.l"
{
	fprintf(tokenfile,"<FLOAT>");
	fprintf(logfile,"Line no. %d: Token <FLOAT> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 294 "1705098.l"
{
	fprintf(tokenfile,"<FOR>");
	fprintf(logfile,"Line no. %d: Token <FOR> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 299 "1705098.l"
{
	fprintf(tokenfile,"<IF>");
	fprintf(logfile,"Line no. %d: Token <IF> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 304 "1705098.l"
{
	fprintf(tokenfile,"<INT>");
	fprintf(logfile,"Line no. %d: Token <INT> Lexeme %s found\n\n",line,yytext);

}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 310 "1705098.l"
{
	fprintf(tokenfile,"<RETURN>");
	fprintf(logfile,"Line no. %d: Token <RETURN> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 315 "1705098.l"
{
	fprintf(tokenfile,"<SWITCH>");
	fprintf(logfile,"Line no. %d: Token <SWITCH> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 320 "1705098.l"
{
	fprintf(tokenfile,"<WHILE>");
	fprintf(logfile,"Line no. %d: Token <WHILE> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 325 "1705098.l"
{
	fprintf(tokenfile,"<VOID>");
	fprintf(logfile,"Line no. %d: Token <VOID> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 330 "1705098.l"
{
	fprintf(tokenfile,"<ADDOP,%s>",yytext);
	fprintf(logfile,"Line no. %d: Token <ADDOP> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 335 "1705098.l"
{
	fprintf(tokenfile,"<MULOP,%s>",yytext);
	fprintf(logfile,"Line no. %d: Token <MULOP> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 340 "1705098.l"
{
	fprintf(tokenfile,"<RELOP,%s>",yytext);
	fprintf(logfile,"Line no. %d: Token <RELOP> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 345 "1705098.l"
{
	fprintf(tokenfile,"<INCOP,%s>",yytext);
	fprintf(logfile,"Line no. %d: Token <INCOP> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 350 "1705098.l"
{
	fprintf(tokenfile,"<LOGICOP,%s>",yytext);
	fprintf(logfile,"Line no. %d: Token <LOGICOP> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 355 "1705098.l"
{
	fprintf(tokenfile,"<BITOP,%s>",yytext);
	fprintf(logfile,"Line no. %d: Token <BITOP> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 360 "1705098.l"
{
	fprintf(tokenfile,"<ASSIGNOP,%s>",yytext);
	fprintf(logfile,"Line no. %d: Token <ASSIGNOP> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 365 "1705098.l"
{
	fprintf(tokenfile,"<NOT,%s>",yytext);
	fprintf(logfile,"Line no. %d: Token <NOT> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 370 "1705098.l"
{
	fprintf(tokenfile,"<LPAREN,%s>",yytext);
	fprintf(logfile,"Line no. %d: Token <LPAREN> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 375 "1705098.l"
{
	fprintf(tokenfile,"<RPAREN,%s>",yytext);
	fprintf(logfile,"Line no. %d: Token <RPAREN> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 380 "1705098.l"
{
	fprintf(tokenfile,"<LCURL,%s>",yytext);
	fprintf(logfile,"Line no. %d: Token <LCURL> Lexeme %s found\n\n",line,yytext);
	st.Enter_Scope();
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 386 "1705098.l"
{
	fprintf(tokenfile,"<RCURL,%s>",yytext);
	fprintf(logfile,"Line no. %d: Token <RCURL> Lexeme %s found\n\n",line,yytext);
	st.Exit_Scope();
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 392 "1705098.l"
{
	fprintf(tokenfile,"<LTHIRD,%s>",yytext);
	fprintf(logfile,"Line no. %d: Token <LTHIRD> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 397 "1705098.l"
{
	fprintf(tokenfile,"<RTHIRD,%s>",yytext);
	fprintf(logfile,"Line no. %d: Token <RTHIRD> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 402 "1705098.l"
{
	fprintf(tokenfile,"<COMMA,%s>",yytext);
	fprintf(logfile,"Line no. %d: Token <COMMA> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 407 "1705098.l"
{
	fprintf(tokenfile,"<SEMICOLON,%s>",yytext);
	fprintf(logfile,"Line no. %d: Token <SEMICOLON> Lexeme %s found\n\n",line,yytext);
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 412 "1705098.l"
{
	fprintf(tokenfile,"<ID,%s>",yytext);
	fprintf(logfile,"Line no. %d: Token <ID> Lexeme %s found\n\n",line,yytext);
	bool did = st.Insert(yytext , "ID" , logfile);
	if(did)st.printall(logfile);
}
	YY_BREAK
case 41:
/* rule 41 can match eol */
YY_RULE_SETUP
#line 419 "1705098.l"
{
	pair<string , int> processed = manipulate_string(yytext);
	fprintf(logfile,"Line no. %d: Token <STRING> Lexeme %s found --> <String , %s>\n",processed.second,yytext,processed.first.c_str());
	fprintf(tokenfile,"<STRING,%s>",processed.first.c_str());
	
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 426 "1705098.l"
{
	error_cnt++;
	fprintf(logfile,"Error at line. %d: Too many decimal points %s\n\n",line,yytext);
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 431 "1705098.l"
{
	error_cnt++;
	fprintf(logfile,"Error at line. %d: Ill formed numer: %s\n\n",line,yytext);
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 436 "1705098.l"
{
	error_cnt++;
	fprintf(logfile,"Error at line. %d: Invalid prefix on ID or invalid suffix on Number %s\n\n",line,yytext);
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 443 "1705098.l"
{
	error_cnt++;
	fprintf(logfile,"Error at line. %d: Empty character constant error %s\n\n",line,yytext);
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 448 "1705098.l"
{
	error_cnt++;
	fprintf(logfile,"Error at line. %d: Unterminated character %s\n\n",line,yytext);
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 453 "1705098.l"
{
	error_cnt++;
	fprintf(logfile,"Error at line. %d: Multi character constant error %s\n\n",line,yytext);
}
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 458 "1705098.l"
{
	error_cnt++;
	int tmp = line;
    newlines_in_comment(yytext); 
	fprintf(logfile,"Error at line. %d: Unterminated comment %s\n\n",tmp,yytext);
}
	YY_BREAK
case 49:
/* rule 49 can match eol */
YY_RULE_SETUP
#line 465 "1705098.l"
{
	error_cnt++;
	int tmp = line;
	pair<string , int> p = manipulate_string(yytext);
	fprintf(logfile,"Error at line. %d: Unterminated string %s\n\n",tmp,yytext);
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 472 "1705098.l"
{
	fprintf(logfile,"Error at line. %d: Unrecgnized character %s\n\n",line,yytext);
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 475 "1705098.l"
ECHO;
	YY_BREAK
#line 1566 "test.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(fnd_multiline_comment):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 271 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 271 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 270);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 475 "1705098.l"


int main(int argc,char *argv[]){
	
	if(argc!=2){
		printf("Please provide input file name and try again\n");
		return 0;
	}
	
	FILE *fin=fopen(argv[1],"r");
	if(fin==NULL){
		printf("Cannot open specified file\n");
		return 0;
	}
	
	
	yyin= fin;
	yylex();
    /*symboltable print dao*/
	fprintf(logfile,"\nTotal Lines : %d\nTotal Errors : %d\n",line,error_cnt);
	fclose(yyin);
	fclose(tokenfile);
	fclose(logfile);
	return 0;
}


